service: cognito-user-example

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  stage: dev

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "dynamodb:PutItem"
     Resource:
      "Fn::GetAtt": [ itemTable, Arn ]
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  include:
   # - include-me.js
  exclude:
#    - exclude-me.js
   - node_modules/**
functions:
  create:
    handler: functions/create.main
    environment:
      TABLE: dev-cognito-user-example-item-table
    events:
      - http:
          method: post
          path: items
          cors: true
          authorizer:
            arn: #arn:aws:cognito-idp:ap-southeast-2:123456789012:userpool/ap-southeast-2_123456789 # Your Cognito User Pool ARN


#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
resources:
  - ${file(resources/user-pool.yml)}
  - ${file(resources/item-table.yml)}


#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
